export const CREATE_POST = 'POST/CREATE_POST';
export const EDIT_POST = 'POST/EDIT_POST';
export const DELETE_POST = 'POST/DELETE_POST';
export const FETCH_POSTS = 'POST/FETCH_POST';

export const SHOW_LOADER = 'POST/SHOW_LOADER';
export const HIDE_LOADER = 'POST/HIDE_LOADER';

export const SHOW_ERROR = 'POST/SHOW_ERROR';
export const HIDE_ERROR = 'POST/HIDE_ERROR';

export const SHOW_COLLAPSE = 'POST/SHOW_COLLAPSE';
export const HIDE_COLLAPSE = 'POST/HIDE_COLLAPSE';